### PR TITLE
DMD 2.066 compatibility and minor dub fixes / improvements

### PR DESCRIPTION
**Pull request by unbornchikken**
- DMD 2.066 compatibility, variadic argument syntax
- Wrapper structures are assignable, previously const(void*) member prevented this
- There wasn't importPath declaration in the dub file, it's added
- Verbose configuration added into dub to help upstream modules find leaks

### CODE REVIEW

**Comment by Trass3r** [comment]
So the previous issues with the ... are fixed?
Do you have example code that lead to your assignment change?

**Comment by unbornchikken** [comment]
Unit tests in wrapper.d file didn't compile without the ... by using DMD 2.066. That's why I added. I ain't find the issue that you mention. Could you please guide me?

**Comment by unbornchikken** [comment]
Today I've identified another issue regarding assignment of structures. Wrapper destructor called before the postblit on the new instance, so the retain is gonna be called after the last release. For example:

CLProgram createAProgram()
{
 auto prg = new CLProgram(...);
 // ... do stuff
 return program;
}

auto myProgram = createProgram();

With the above code myProgram will hold a program instance whose released to ref count of zero then retained again. With AMD OpenCL the queried ref count will be 0xFFFFFFFF for myProgram.

Maybe I can fix this by adding an opAssign implementation, and in this case the ugly a6eba06 commit won't needed anymore (without it the above sample code won't compile).

**Comment by Trass3r** [comment]
Well some people seemed to have issues with the `...` and removed it.

Allocating these objects on the heap is quite strange as you lose deterministic behavior.
Also note that this is currently broken, the destructor is not always called by the GC.

I only see construction in there, no assignment. Do you have sample code which shows a real use-case for assignment?

That destructor being called first sounds strange.

**Comment by unbornchikken** [comment]
Hi. Sorry, it was late night and I funked up my example code.

suto prg = CLProgram(...)

so there is no heap involved. The problem is postblit operator is not copy construtor, and if there is an assignment, it will called after the original objet destructor as I stated.

Postblit also prevented assignment compile in your version since _object is const, so thats why noone reported it before.

**Comment by unbornchikken** [comment]
auto prg

I'm sittin on the toilet an holding my phone sorry for the typos. 😊

**Comment by Trass3r** [comment]
:D
Will need to test this myself when I find time.
There's also another branch about trying to switch to DerelictCL. They don't use const at all on the types. good and bad.

**Comment by unbornchikken** [comment]
I've finished my changes to support assignment on all CL structs. The problem was that there is a new state involved, when _object is null, if the struct is assignable. Also I dropped const from void*, this is nicer approach than the cast in my previous commit. Please wait for me to propose an other PR in which I'm adding binary support to programs beside the assignment support. I have a repo with a bunch of opencl unit test where I can show you how the above fare before accepting the changes.

**Comment by unbornchikken** [comment]
I've finished my changes. You can merge them if you want. 
- DMD 2.066 compatibility, variadic argument syntax
- Wrapper structures are assignable, previously const(void*) member prevented this
- There wasn't importPath declaration in the dub file, it's added
- Verbose configuration added into dub to help upstream modules find leaks
- Programs are creatable from binaries
- GDC 4.9.1 compatibility
- Various fixes and improvements

I have some OpenCL related unit test there: https://github.com/unbornchikken/neuroflow-D

Works well on:

Win/Linux: DMD 2.066, LDC 0.15, GDC 4.9.1

**Pull request closed without merging**
